<?php

/**
 * Implement hook_mail().
 */
function ppss_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'cancel_subscription':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);
     $message['body'][] = $params['message'];
     break;
 }
}

/**
 * Implements hook_cron().
 */
function ppss_cron(){
  //desactivar planes de usuarios que han cancelado suscripción
  $today = strtotime(date('d-m-Y'));
  //obtener registros de ventas con fecha de vencimiento 
  $query = \Drupal::database()->select('ppss_sales', 's');
  $query->condition('expire', $today);
  $query->fields('s', ['id', 'uid', 'id_role', 'mail']);
  $query->orderBy('id', 'DESC');
  $results = $query->execute()->fetchAll();
  foreach($results as $subscription) {
    //actualizar la tabla de ppss_sales
    \Drupal::database()->update('ppss_sales')->fields([
      'status' => 0,
    ])->condition('id', $subscription->id, '=')->execute();
    //Eliminar rol asignado de la suscripción del usuario 
    try {
      $user = \Drupal\user\Entity\User::load($subscription->uid); 
      $user->removeRole($subscription->id_role);
      $user->save();
      $msg_info = 'Se ha cancelado la suscripción de plan '.$subscription->id_role.' del usuario '.$subscription->uid;
      $msg_user = 'La suscripción ha sido cancelada,';
    } catch (\Exception $e) {
      \Drupal::logger('PPSS')->error($e->getMessage());
    }
    \Drupal::logger('PPSS')->info($msg_info);
    $msg = '<div style="text-align: center;  margin: 20px;">
    <h1> !Cancelación de suscripción en Encuéntralo! &#128577;</h1>
    <br><div style="text-align: center; font-size: medium;">'.$msg_user.
    ' sin embargo cuentas con la opción Gratis para continuar publicando tus anuncios o puedes volver a contratar alguno de nuestros <a href=“https://www.encuentralo.digital/planes”>Planes</a>.
    </div><br><br>
    <div style="text-align: center; border-top: 1px solid #bdc1c6; padding-top: 20px; font-style: italic; font-size: medium; color: #83878c;"><br>--  El equipo de [site:name]</div></div>';

    //Enviar correo a usuario y marketing
    $module = 'ppss';
    $key = 'cancel_subscription';
    $to = $subscription->mail."; marketing@noticiasnet.mx";
    $params['message'] = $msg;
    $params['subject'] = "Cancelación de suscripción - Encuéntralo";
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;
    $result = \Drupal::service('plugin.manager.mail')->mail($module, $key, $to, $langcode, $params, NULL, $send);
    if ($result['result'] !== true) {
      \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent.'), 'error');
    }
    else {
      \Drupal::messenger()->addMessage(t('Your message has been sent.'));
    }
  }
}