<?php

/**
 * Implement hook_mail().
 */
function ppss_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'cancel_subscription':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('@subject', ['@subject' => $params['subject']], $options);
     $message['body'][] = $params['message'];
     break;
 }
}

/**
 * Implements hook_cron().
 */
function ppss_cron(){
  //disable user subscription
  $today = strtotime(date('d-m-Y'));
  //get sales with expiration date 
  $query = \Drupal::database()->select('ppss_sales', 's');
  $query->condition('expire', $today);
  $query->condition('status', 1, '=');
  $query->fields('s', ['id', 'uid', 'id_role', 'mail']);
  $query->orderBy('id', 'DESC');
  $results = $query->execute()->fetchAll();
  foreach($results as $subscription) {
    // Update status ppss_sales table
    \Drupal::database()->update('ppss_sales')->fields([
      'status' => 0,
    ])->condition('id', $subscription->id, '=')->execute();
    // Remove user role added by subscription purchased
    try {
      $user = \Drupal\user\Entity\User::load($subscription->uid); 
      $user->removeRole($subscription->id_role);
      $user->save();
      $msg_info = 'Se ha cancelado la suscripción de plan '.$subscription->id_role.' del usuario '.$subscription->uid;
      $msg_user = 'Tu suscripción ha sido cancelada,';
    } catch (\Exception $e) {
      \Drupal::logger('PPSS')->error($e->getMessage());
    }
    \Drupal::logger('PPSS')->info($msg_info);

    // Unpublish ads posted after scheduling plan cancellation
    // Get content type based on role
    if ($subscription->id_role == 'enterprise') {
      $typeContent = "nvi_anuncios_e";
    } elseif($subscription->id_role == 'comercial') {
      $typeContent = "nvi_anuncios_c";
    } elseif($subscription->id_role == 'basic') {
      $typeContent = "nvi_anuncios_b";
    }
    // Get all user ads by content type
    $nids = \Drupal::entityQuery("node")->condition('uid', $subscription->uid)
      ->condition('type', $typeContent)->condition('status', 1)->execute();
    $entity = \Drupal::entityTypeManager()->getStorage("node");
    $nodes = $entity->loadMultiple($nids);
    // Unpublish all ads
    foreach ($nodes as $node) {
      $node->unpublish_on = strtotime(date('d-m-Y H:i:s'));;
      $node->setUnpublished();
      $node->save();
    }

    $msg = '<div style="text-align: center;  margin: 20px;">
    <h1> ¡Hasta pronto! </h1>
    <h1> ¡Cancelación de suscripción en Encuéntralo! &#128522;</h1>
    <br><div style="text-align: center; font-size: 24px;">'.$msg_user.' mientras tanto recuerda que puedes continuar publicando anuncios con la versión gratuita.
    </div><br><br>
    <div style="text-align: center; border-top: 1px solid #bdc1c6; padding-top: 20px; font-style: italic; font-size: medium; color: #83878c;"><br>--  El equipo de Encuéntralo</div></div>';

    // Send alert by email to stakeholders
    $module = 'ppss';
    $key = 'cancel_subscription';
    $to = $user->getEmail().";".\Drupal::config('system.site')->get('mail');
    $params['message'] = $msg;
    $params['subject'] = "Cancelación de suscripción - Encuéntralo";
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = true;
    $result = \Drupal::service('plugin.manager.mail')->mail($module, $key, $to, $langcode, $params, NULL, $send);
    if ($result['result'] != true) {
      $msg_mail = t('There was a problem sending your message and it was not sent.');
    }
    else {
      $msg_mail = t('Your email has been sent.');
    }
    \Drupal::logger('PPSS')->info($msg_mail);
  }
}