ppss.settings:
  type: config_object
  label: PPSS Settings
  mapping:
    client_id:
      type: string
    client_secret:
      type: string
    payment_type:
      type: sequence
      label: Payment types the PPSS Form can display on
      sequence:
        type: string
        label: Payment type
    sandbox_mode:
      type: boolean
    field_price:
      type: string
    field_description:
      type: string
    field_sku:
      type: string
    currency_code:
      type: string
    tax:
      type: string