ppss.settings:
  type: config_object
  label: PPSS Settings

  mapping:
    allowed_gateways:
      type: sequence
      label: Payment gateways the PPSS Form can display on it
      sequence:
        type: string
        label: Payment gateway
    content_types:
      type: sequence
      label: Content types the PPSS Form can display on it
      sequence:
        type: string
        label: Content type
    client_id:
      type: string
    client_secret:
      type: string
    sandbox_mode:
      type: boolean
    field_price:
      type: string
    field_frequency:
      type: string
    field_frequency_interval:
      type: string
    field_description:
      type: string
    field_sku:
      type: string
    field_role:
      type: string
    currency_code:
      type: string
    tax:
      type: string
    success_url:
      type: string
    error_url:
      type: string